-- ============================================================
-- Motor JARVIS - VERSÃO COMPLETA: todas 10 regras
-- Adiciona R01 (ativo < CDI) e R04 (veículo TCO) ao scanner
-- Versão final: R01-R10 + R03b + Camada 2 Combinador
-- Substitui get_jarvis_scan das migrations 068 e 070
-- Ref: FINANCIAL-METHODOLOGY.md §6
-- ============================================================
-- Nota: função completa aplicada via Supabase MCP (apply_migration).
-- Este arquivo contém documentação da versão canônica.
-- A função live no DB é a fonte de verdade.
SELECT 1;
